image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages:
  - build
  - test
  - release

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-auth:
  stage: build
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/auth
    CONTAINER_TEST_IMAGE: $IMAGE_NAME:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $IMAGE_NAME:latest
  script:
    - docker build --build-arg GITLAB_TOKEN=$GITLAB_TOKEN --pull -t $CONTAINER_TEST_IMAGE ./auth
    - docker push $CONTAINER_TEST_IMAGE

build-tickets:
  stage: build
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/tickets
    CONTAINER_TEST_IMAGE: $IMAGE_NAME:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $IMAGE_NAME:latest
  script:
    - docker build --build-arg GITLAB_TOKEN=$GITLAB_TOKEN --pull -t $CONTAINER_TEST_IMAGE ./tickets
    - docker push $CONTAINER_TEST_IMAGE
