apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: 1337148.com:5050/jd/ticketing/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CI_JOB_TOKEN: "{{.GITLAB_TOKEN}}"
          CI_API_V4_URL: "https://1337148.com/api/v4"
          CI_PROJECT_ID: "20"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: 1337148.com:5050/jd/ticketing/client
      context: ./client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: 1337148.com:5050/jd/ticketing/tickets
      context: ./tickets
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CI_JOB_TOKEN: "{{.GITLAB_TOKEN}}"
          CI_API_V4_URL: "https://1337148.com/api/v4"
          CI_PROJECT_ID: "20"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: 1337148.com:5050/jd/ticketing/orders
      context: ./orders
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CI_JOB_TOKEN: "{{.GITLAB_TOKEN}}"
          CI_API_V4_URL: "https://1337148.com/api/v4"
          CI_PROJECT_ID: "20"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: 1337148.com:5050/jd/ticketing/expiration
      context: ./expiration
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CI_JOB_TOKEN: "{{.GITLAB_TOKEN}}"
          CI_API_V4_URL: "https://1337148.com/api/v4"
          CI_PROJECT_ID: "20"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
