.client-config:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/client
    CONTAINER_TEST_IMAGE: $IMAGE_NAME:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $IMAGE_NAME:latest

build-client:
  stage: build
  extends: .client-config
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE ./client
    - docker push $CONTAINER_TEST_IMAGE

release-client:
  stage: release
  extends: .client-config
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main
